services:
  score: # Script
    build: scorer
  database: # Database
    build: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
  server: # Base server
    build: server
  client: # cli client
    build: client


